# Generated by Django 5.0.6 on 2024-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_productinvoice_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinvoice',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
