# Generated by Django 5.0.6 on 2025-05-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_productinvoice_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrate',
            name='rate_history',
            field=models.JSONField(blank=True, null=True, verbose_name='rate history'),
        ),
    ]
